language: php
dist: trusty
php:
  - 7.0
  - hhvm

sudo: false

env: SYMFONY_VERSION=3.2.*

cache:
  directories:
    - $HOME/.composer/cache/files

matrix:
  include:
    - php: 7.1
      env: STABILITY=dev SYMFONY_VERSION=3.3.*
    - php: 5.6
      env: SYMFONY_VERSION=2.8.* COMPOSER_FLAGS="--prefer-lowest"
    - php: 7.1
      env: SYMFONY_VERSION=3.1.*
  fast_finish: true

before_install:
  - phpenv config-rm xdebug.ini || true
  - composer self-update
  - ${STABILITY:+ composer config 'minimum-stability' "$STABILITY"}
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require symfony/symfony:${SYMFONY_VERSION} --no-update; fi

install: composer update --prefer-dist $COMPOSER_FLAGS

before_script: vendor/bin/phpunit --version

script: vendor/bin/phpunit

notifications:
  irc: "irc.freenode.org#symfony-cmf"
