language: php

php:
    - 5.3
    - 5.4
    - 5.5
    - hhvm

before_script:
  - composer self-update
  - composer install

script: 
  - phpunit

notifications:
  irc: "irc.freenode.org#symfony-cmf"
  email: "symfony-cmf-devs@googlegroups.com"

matrix:
  allow_failures:
    - env: SYMFONY_VERSION=dev-master
    - php: hhvm
